### ISSUE TITLE
Format-Fehler beim Speichern

### ISSUE THREAD

**Issue by ghost** [maximusx64/loweralphanotation#1]
Hallo zusammen,
beim Speichern eines Programms in eine Datei werden das Alpha und das Rho nicht richtig in die Datei geschrieben, sondern durch ein "?" ersetz, so dass man das Programm nicht erneut laden kann.

**Comment by SirkoHoeer** [comment]
Hallo Jonas,

vielen Dank für die Report.

Das Problem ist uns bekannt und wir versuchen es noch zu beheben. Es ist 
ein Konflikt mit den Char-Set von Windows. Unter Linux
oder MacOS funktioniert es. Die einzige derzeitige Möglichkeit ist den 
Inhalt aus der IDE zu kopieren und danach in eine leere Datei einzufügen.

Danach kann man dann die jeweilige Datei laden.

Viele Grüße,

Sirko

Am 02.06.17 um 14:48 schrieb Jonas T.:

**Comment by Qwerty0x64** [comment]
Also ich hab keine Probleme auf Windows mit dem Charset. 
Beim Speichern, schreibt er in die datei wirklich ein ρ und beim laden auch.
Wenn ich datei mit einem anderen Editor oeffne ergibt sich genau so ein ρ.

Welches Windows hast du?

**Comment by Qwerty0x64** [comment]
>

**Comment by Qwerty0x64** [comment]
So, wir haben gerade herausgefunden das bis windows 7 inclusive der standard charset ansi ist, erst ab  win 8 ist es utf8. daher kommt die codierungsprobleme.
